use std::geo2d::*;
use std::ops::*;

//const COVER_WIDTH = 291mm;
//const COVER_HEIGHT = 138mm;
//const COVER_DEPTH = 3mm;

const TOP_DUCT_DEPTH = 200mm;
const TOP_DUCT_ANGLE = 30deg;

const HOLE_WIDTH = 238mm;
const HOLE_HEIGHT = 88mm;

//const NUM_SLATS = 10;
//const FRACTION_OPEN = 3.0 / 4.0;

const DUCT_WIDTH = 246mm;
const DUCT_HEIGHT = 97mm;
const DUCT_DEPTH = 45mm;

// Because I don't know how to do trig in microcad yet. (Is it supported?)
const SIN_90_DEG = 1.0;
const SIN_TOP_DUCT_ANGLE = 0.86602540378; // sin(60deg)
//const SIN_TOP_DUCT_OTHER_ANGLE = 0.5; // sin(30deg)
const COS_OTHER_ANGLE = 0.5; // cos(60deg)
const COS_ANGLE = 0.86602540378; // cos(30deg)

part TopDuct() {
    //angled_duct_height = DUCT_HEIGHT * (SIN_90_DEG / SIN_TOP_DUCT_ANGLE);
    //angled_hole_height = HOLE_HEIGHT * (SIN_90_DEG / SIN_TOP_DUCT_ANGLE);
    angled_duct_height = DUCT_HEIGHT / COS_ANGLE;
    angled_hole_height = HOLE_HEIGHT / COS_ANGLE;

    std::print(angled_duct_height);

    duct = Rect(width = DUCT_WIDTH, height = angled_duct_height);
    duct_hole = Rect(width = HOLE_WIDTH, height = angled_hole_height);

    bottom_corner_lift = (DUCT_HEIGHT / 2) * (SIN_90_DEG/SIN_TOP_DUCT_ANGLE);

    angled_duct = (duct - duct_hole)
        .extrude(height = TOP_DUCT_DEPTH)
        .rotate(x = TOP_DUCT_ANGLE)
        .translate(z = bottom_corner_lift * 0.5);

    bottom_chop = Rect(width = DUCT_WIDTH * 2, height = angled_duct_height * 2)
        // Should be .extrude(-1 * TOP_DUCT_DEPTH);,
        // but I suspect there is either a bug in microcad or I don't understand something
        .extrude(TOP_DUCT_DEPTH)
        .translate(z = -1 * TOP_DUCT_DEPTH);

    angled_duct - bottom_chop;
}

/*
sketch Top() {
    top = Rect(width = COVER_WIDTH, height = COVER_HEIGHT);

    slat_hole_width = (HOLE_WIDTH / (NUM_SLATS + 1)) * FRACTION_OPEN;
    slat_hole = Rect(width = slat_hole_width, height = HOLE_HEIGHT);

    holes = slat_hole.translate(x = ([0..NUM_SLATS] * (HOLE_WIDTH / NUM_SLATS)) - (HOLE_WIDTH / 2));

    top - holes;
}
*/

sketch Bottom() {
    duct = Rect(width = DUCT_WIDTH, height = DUCT_HEIGHT);
    duct_hole = Rect(width = HOLE_WIDTH, height = HOLE_HEIGHT);

    duct - duct_hole;
}

Bottom().extrude(-DUCT_DEPTH);
TopDuct();
//Top().extrude(COVER_DEPTH);
